name: Build and push docker image

# This workflow is triggered when a branch is pushed
# If it is main branch then it will build and push docker image

on:
  push:
    branches:
      - "*"

env:
  DENO_VERSION: 1.39.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # if you need to checkout submodules, uncomment the following line (github token is required)
        # with:
        #   token: ${{ secrets.ORG_GITHUB_TOKEN }}
        #   submodules: recursive

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Lint
        run: deno task lint

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE }}:latest
