name: Release new version

# This workflow is triggered when a new tag is pushed to the repository.
# Tag name must be in the format v1.0.0, docker image will be tagged with 1.0.0.

on:
  push:
    tags:
      - "*"

env:
  DENO_VERSION: 1.39.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # if you need to checkout submodules, uncomment the following line (github token is required)
        # with:
        #   token: ${{ secrets.ORG_GITHUB_TOKEN }}
        #   submodules: recursive

      - name: Define tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Lint
        run: deno task lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image (tagged)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE }}:${{ env.TAG }}

      # Uncomment the following lines if you want to update deployment tag in digitalocean app platform

      # - name: Update deployment tag
      #   run: deno run --allow-env --allow-net https://cdn.jsdelivr.net/gh/ball6847/do-app-updater@631ac8a/cli.ts --id ${{ vars.APP_ID }} --tag ${{ env.TAG }} --service ${{ vars.SERVICE_NAME }}
      #   env:
      #     DO_ACCESS_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
